import crypto from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { ApiError } from "../../common/api-error.js";
import { asyncHandler } from "../../common/async-handler.js";
import { parse } from "../../common/validation.js";
import { Player } from "../players/player.model.js";
import { FriendRequest, SocialRoom, SocialRoomDocument } from "./social.model.js";

export const socialRouter = Router();
const person = z.object({ playerId: z.string().trim().min(3).max(80), name: z.string().trim().min(2).max(30) });
const roomShape = (room: SocialRoomDocument) => ({ id: room.id, name: room.name, hostId: room.hostId, mode: room.mode, members: room.members, messages: room.messages.slice(-50), status: room.status });

socialRouter.post("/identity", asyncHandler(async (req, res) => { const input = parse(z.object({ id: z.string().trim().min(3).max(80).optional(), name: z.string().trim().min(2).max(30) }), req.body); const id = input.id ?? `sp_${crypto.randomUUID()}`; const player = await Player.findOneAndUpdate({ id }, { $set: { name: input.name } }, { new: true, upsert: true, setDefaultsOnInsert: true }); res.status(201).json({ player: { id: player.id, name: player.name } }); }));
socialRouter.get("/friends", asyncHandler(async (req, res) => { const playerId = String(req.query.playerId ?? ""); if (!playerId) throw new ApiError(400, "INVALID_INPUT", "playerId is required."); const requests = await FriendRequest.find({ $or: [{ fromId: playerId }, { toId: playerId }] }).sort({ createdAt: -1 }); res.json({ data: requests.map((item) => ({ id: item.id, status: item.status, direction: item.fromId === playerId ? "sent" : "received", player: item.fromId === playerId ? { id: item.toId, name: item.toName } : { id: item.fromId, name: item.fromName } })) }); }));
socialRouter.post("/friends/request", asyncHandler(async (req, res) => { const input = parse(z.object({ from: person, to: z.object({ playerId: z.string().trim().min(3).max(80) }) }).refine(({ from, to }) => from.playerId !== to.playerId, "Choose another player."), req.body); const target = await Player.findOne({ id: input.to.playerId }); if (!target) throw new ApiError(404, "PLAYER_NOT_FOUND", "That player has not joined Nexora Social yet."); const existing = await FriendRequest.findOne({ $or: [{ fromId: input.from.playerId, toId: input.to.playerId }, { fromId: input.to.playerId, toId: input.from.playerId }] }); if (existing) throw new ApiError(409, "FRIEND_REQUEST_EXISTS", "A friend connection already exists."); const request = await FriendRequest.create({ id: `fr_${crypto.randomUUID()}`, fromId: input.from.playerId, fromName: input.from.name, toId: target.id, toName: target.name }); res.status(201).json({ id: request.id, status: request.status }); }));
socialRouter.post("/friends/:id/accept", asyncHandler(async (req, res) => { const playerId = parse(z.object({ playerId: z.string().min(3) }), req.body).playerId; const request = await FriendRequest.findOne({ id: String(req.params.id), toId: playerId }); if (!request) throw new ApiError(404, "FRIEND_REQUEST_NOT_FOUND", "Friend request not found."); request.status = "accepted"; await request.save(); res.json({ id: request.id, status: request.status }); }));
socialRouter.get("/rooms", asyncHandler(async (_req, res) => { const rooms = await SocialRoom.find({ status: "open" }).sort({ createdAt: -1 }).limit(30); res.json({ data: rooms.map((room) => roomShape(room)) }); }));
socialRouter.post("/rooms", asyncHandler(async (req, res) => { const input = parse(z.object({ host: person, name: z.string().trim().min(3).max(50), mode: z.enum(["duel", "team"]) }), req.body); const room = await SocialRoom.create({ id: `rm_${crypto.randomUUID()}`, name: input.name, hostId: input.host.playerId, mode: input.mode, members: [{ playerId: input.host.playerId, name: input.host.name, ...(input.mode === "team" ? { team: "violet" } : {}) }] }); res.status(201).json({ room: roomShape(room) }); }));
socialRouter.post("/rooms/:id/join", asyncHandler(async (req, res) => { const member = parse(person, req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "open" }); if (!room) throw new ApiError(404, "ROOM_NOT_FOUND", "This lobby is no longer available."); const cap = room.mode === "duel" ? 2 : 8; if (!room.members.some((item) => item.playerId === member.playerId)) { if (room.members.length >= cap) throw new ApiError(409, "ROOM_FULL", "This lobby is full."); room.members.push({ ...member, ...(room.mode === "team" ? { team: room.members.filter((item) => item.team === "violet").length <= room.members.filter((item) => item.team === "cyan").length ? "violet" : "cyan" } : {}) }); await room.save(); } res.json({ room: roomShape(room) }); }));
socialRouter.get("/rooms/:id", asyncHandler(async (req, res) => { const room = await SocialRoom.findOne({ id: String(req.params.id) }); if (!room) throw new ApiError(404, "ROOM_NOT_FOUND", "Lobby not found."); res.json({ room: roomShape(room) }); }));
