import crypto from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { ApiError } from "../../common/api-error.js";
import { asyncHandler } from "../../common/async-handler.js";
import { parse } from "../../common/validation.js";
import { Player } from "../players/player.model.js";
import { FriendRequest, SocialRoom, SocialRoomDocument } from "./social.model.js";
import { Category } from "../categories/category.model.js";
import { answersMatch, selectQuestions } from "../questions/question.service.js";
import { emitRoom } from "../../realtime.js";

export const socialRouter = Router();
const person = z.object({ playerId: z.string().trim().min(3).max(80), name: z.string().trim().min(2).max(30) });
const roomShape = (room: SocialRoomDocument, playerId?: string) => { const match = room.match; const scores = room.members.map((member) => ({ playerId: member.playerId, name: member.name, team: member.team, score: match?.answers.filter((a) => a.playerId === member.playerId).reduce((sum, a) => sum + a.points, 0) ?? 0, answered: match?.answers.filter((a) => a.playerId === member.playerId).length ?? 0, quit: match?.quitPlayerIds.includes(member.playerId) ?? false })); const canSeeCurrentQuestion = room.mode === "duel" || match?.turnPlayerId === playerId; const current = match && canSeeCurrentQuestion && match.turnPlayerId ? match.questions[match.answers.length] : undefined; return { id: room.id, name: room.name, hostId: room.hostId, mode: room.mode, members: room.members, messages: room.messages.slice(-50), status: room.status, match: match ? { categoryId: match.categoryId, categoryName: match.categoryName, questionCount: match.questionCount, timePerQuestionSeconds: match.timePerQuestionSeconds, turnPlayerId: match.turnPlayerId, turnStartedAt: match.turnStartedAt?.toISOString(), scores, totalAnswered: match.answers.length, answers: match.answers.map((answer) => ({ playerId: answer.playerId, questionIndex: answer.questionIndex, status: answer.status, points: answer.points })), currentQuestion: current && { id: current.questionId, question: current.question, difficulty: current.difficulty, explanation: current.explanation } } : undefined }; };
const activeMembers = (room: SocialRoomDocument) => room.members.filter((m) => !room.match?.quitPlayerIds.includes(m.playerId));
function advanceTurn(room: SocialRoomDocument) { const match = room.match!; const eligible = activeMembers(room).filter((m) => match.answers.filter((a) => a.playerId === m.playerId).length < match.questionCount); const teamAlive = room.mode !== "team" || ["violet", "cyan"].every((team) => activeMembers(room).some((m) => m.team === team)); if (!eligible.length || !teamAlive) { room.status = "completed"; match.turnPlayerId = undefined; return; } const previous = match.turnPlayerId; const at = Math.max(0, eligible.findIndex((m) => m.playerId === previous)); match.turnPlayerId = eligible[(at + 1) % eligible.length].playerId; match.turnStartedAt = new Date(); }

socialRouter.post("/identity", asyncHandler(async (req, res) => { const input = parse(z.object({ id: z.string().trim().min(3).max(80).optional(), name: z.string().trim().min(2).max(30) }), req.body); const id = input.id ?? `sp_${crypto.randomUUID()}`; const player = await Player.findOneAndUpdate({ id }, { $set: { name: input.name } }, { new: true, upsert: true, setDefaultsOnInsert: true }); res.status(201).json({ player: { id: player.id, name: player.name } }); }));
socialRouter.get("/friends", asyncHandler(async (req, res) => { const playerId = String(req.query.playerId ?? ""); if (!playerId) throw new ApiError(400, "INVALID_INPUT", "playerId is required."); const requests = await FriendRequest.find({ $or: [{ fromId: playerId }, { toId: playerId }] }).sort({ createdAt: -1 }); res.json({ data: requests.map((item) => ({ id: item.id, status: item.status, direction: item.fromId === playerId ? "sent" : "received", player: item.fromId === playerId ? { id: item.toId, name: item.toName } : { id: item.fromId, name: item.fromName } })) }); }));
socialRouter.post("/friends/request", asyncHandler(async (req, res) => { const input = parse(z.object({ from: person, to: z.object({ playerId: z.string().trim().min(3).max(80) }) }).refine(({ from, to }) => from.playerId !== to.playerId, "Choose another player."), req.body); const target = await Player.findOne({ id: input.to.playerId }); if (!target) throw new ApiError(404, "PLAYER_NOT_FOUND", "That player has not joined Nexora Social yet."); const existing = await FriendRequest.findOne({ $or: [{ fromId: input.from.playerId, toId: input.to.playerId }, { fromId: input.to.playerId, toId: input.from.playerId }] }); if (existing) throw new ApiError(409, "FRIEND_REQUEST_EXISTS", "A friend connection already exists."); const request = await FriendRequest.create({ id: `fr_${crypto.randomUUID()}`, fromId: input.from.playerId, fromName: input.from.name, toId: target.id, toName: target.name }); res.status(201).json({ id: request.id, status: request.status }); }));
socialRouter.post("/friends/:id/accept", asyncHandler(async (req, res) => { const playerId = parse(z.object({ playerId: z.string().min(3) }), req.body).playerId; const request = await FriendRequest.findOne({ id: String(req.params.id), toId: playerId }); if (!request) throw new ApiError(404, "FRIEND_REQUEST_NOT_FOUND", "Friend request not found."); request.status = "accepted"; await request.save(); res.json({ id: request.id, status: request.status }); }));
socialRouter.get("/rooms", asyncHandler(async (_req, res) => { const rooms = await SocialRoom.find({ status: "open" }).select({ _id: 0, id: 1, name: 1, hostId: 1, mode: 1, members: 1, status: 1 }).sort({ createdAt: -1 }).limit(30).lean(); res.set("Cache-Control", "private, max-age=5, stale-while-revalidate=30"); res.json({ data: rooms }); }));
socialRouter.post("/rooms", asyncHandler(async (req, res) => { const input = parse(z.object({ host: person, name: z.string().trim().min(3).max(50), mode: z.enum(["duel", "team"]) }), req.body); const room = await SocialRoom.create({ id: `rm_${crypto.randomUUID()}`, name: input.name, hostId: input.host.playerId, mode: input.mode, members: [{ playerId: input.host.playerId, name: input.host.name, ...(input.mode === "team" ? { team: "violet" } : {}) }] }); res.status(201).json({ room: roomShape(room) }); }));
socialRouter.post("/rooms/:id/join", asyncHandler(async (req, res) => { const member = parse(person, req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "open" }); if (!room) throw new ApiError(404, "ROOM_NOT_FOUND", "This lobby is no longer available."); const cap = room.mode === "duel" ? 2 : 8; if (!room.members.some((item) => item.playerId === member.playerId)) { if (room.members.length >= cap) throw new ApiError(409, "ROOM_FULL", "This lobby is full."); room.members.push({ ...member, ...(room.mode === "team" ? { team: room.members.filter((item) => item.team === "violet").length <= room.members.filter((item) => item.team === "cyan").length ? "violet" : "cyan" } : {}) }); await room.save(); emitRoom(room.id, "room:update", roomShape(room)); } res.json({ room: roomShape(room) }); }));
socialRouter.post("/rooms/:id/leave", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string() }), req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "open" }); if (!room) throw new ApiError(409, "ROOM_NOT_OPEN", "This lobby can no longer be left."); if (room.hostId === input.playerId) throw new ApiError(403, "HOST_MUST_DELETE", "The lobby creator must delete the lobby."); room.members = room.members.filter((member) => member.playerId !== input.playerId); await room.save(); emitRoom(room.id, "room:update", roomShape(room)); res.json({ room: roomShape(room) }); }));
socialRouter.delete("/rooms/:id", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string() }), req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "open" }); if (!room) throw new ApiError(404, "ROOM_NOT_FOUND", "This open lobby no longer exists."); if (room.hostId !== input.playerId) throw new ApiError(403, "HOST_ONLY", "Only the lobby creator can delete it."); await room.deleteOne(); emitRoom(room.id, "room:deleted", { roomId: room.id }); res.status(204).end(); }));
socialRouter.post("/rooms/:id/start", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string(), categoryId: z.string(), questionCount: z.number().int().min(1).max(50), timePerQuestionSeconds: z.number().int().min(10).max(300) }), req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: { $in: ["open", "completed"] } }); if (!room) throw new ApiError(409, "ROOM_NOT_READY", "This lobby cannot be started."); if (room.hostId !== input.playerId) throw new ApiError(403, "HOST_ONLY", "Only the lobby creator can start the match."); if (room.mode === "duel" && room.members.length !== 2) throw new ApiError(409, "PLAYERS_REQUIRED", "A 1v1 needs exactly two players."); if (room.mode === "team" && !["violet", "cyan"].every((team) => room.members.some((m) => m.team === team))) throw new ApiError(409, "TEAMS_REQUIRED", "Each team needs at least one player."); const category = await Category.findOne({ id: input.categoryId, active: true }); if (!category) throw new ApiError(404, "CATEGORY_NOT_FOUND", "Category not found."); const questions = await selectQuestions(input.categoryId, input.questionCount * room.members.length, "mixed"); room.status = "active"; room.match = { categoryId: category.id, categoryName: category.name, questionCount: input.questionCount, timePerQuestionSeconds: input.timePerQuestionSeconds, questions: questions.map((q) => ({ questionId: q.id, question: q.question, answer: q.answer, acceptedAnswers: q.acceptedAnswers, explanation: q.explanation, difficulty: q.difficulty })), answers: [], turnPlayerId: room.members[0].playerId, turnStartedAt: new Date(), quitPlayerIds: [] }; await room.save(); emitRoom(room.id, "match:update", roomShape(room)); res.json({ room: roomShape(room, input.playerId) }); }));
socialRouter.post("/rooms/:id/answer", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string(), answer: z.string().max(1000).default("") }), req.body); const answer = input.answer ?? ""; const room = await SocialRoom.findOne({ id: String(req.params.id), status: "active" }); if (!room?.match) throw new ApiError(409, "MATCH_NOT_ACTIVE", "Match is not active."); const match = room.match; if (match.turnPlayerId !== input.playerId) throw new ApiError(409, "NOT_YOUR_TURN", "Wait for your turn."); const questionIndex = match.answers.length; const question = match.questions[questionIndex]; const expired = Date.now() > (match.turnStartedAt?.getTime() ?? 0) + match.timePerQuestionSeconds * 1000; const status = !answer.trim() || expired ? "unanswered" : answersMatch(answer, question) ? "correct" : "incorrect"; match.answers.push({ playerId: input.playerId, questionIndex, answer, status, points: status === "correct" ? 10 : 0 }); advanceTurn(room); await room.save(); emitRoom(room.id, "match:update", roomShape(room)); res.json({ room: roomShape(room, input.playerId), result: { status, correctAnswer: question.answer, explanation: question.explanation } }); }));
socialRouter.post("/rooms/:id/quit", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string() }), req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "active" }); if (!room?.match) throw new ApiError(409, "MATCH_NOT_ACTIVE", "Match is not active."); if (!room.match.quitPlayerIds.includes(input.playerId)) room.match.quitPlayerIds.push(input.playerId); if (room.match.turnPlayerId === input.playerId) advanceTurn(room); await room.save(); emitRoom(room.id, "match:update", roomShape(room)); res.json({ room: roomShape(room, input.playerId) }); }));
socialRouter.post("/rooms/:id/restart", asyncHandler(async (req, res) => { const input = parse(z.object({ playerId: z.string() }), req.body); const room = await SocialRoom.findOne({ id: String(req.params.id), status: "completed" }); if (!room?.match) throw new ApiError(409, "MATCH_NOT_COMPLETE", "This match cannot be restarted yet."); if (room.hostId !== input.playerId) throw new ApiError(403, "HOST_ONLY", "Only the lobby creator can restart the quiz."); const previous = room.match; const questions = await selectQuestions(previous.categoryId, previous.questionCount * room.members.length, "mixed"); room.status = "active"; room.match = { categoryId: previous.categoryId, categoryName: previous.categoryName, questionCount: previous.questionCount, timePerQuestionSeconds: previous.timePerQuestionSeconds, questions: questions.map((q) => ({ questionId: q.id, question: q.question, answer: q.answer, acceptedAnswers: q.acceptedAnswers, explanation: q.explanation, difficulty: q.difficulty })), answers: [], turnPlayerId: room.members[0]?.playerId, turnStartedAt: new Date(), quitPlayerIds: [] }; await room.save(); emitRoom(room.id, "match:update", roomShape(room)); res.json({ room: roomShape(room, input.playerId) }); }));
socialRouter.get("/rooms/:id", asyncHandler(async (req, res) => { const room = await SocialRoom.findOne({ id: String(req.params.id) }); if (!room) throw new ApiError(404, "ROOM_NOT_FOUND", "Lobby not found."); res.json({ room: roomShape(room, typeof req.query.playerId === "string" ? req.query.playerId : undefined) }); }));
