import { connectDatabase } from "../config/database.js";
import { Category } from "../modules/categories/category.model.js";
import { Question, Difficulty } from "../modules/questions/question.model.js";

const categories = [
  { id: "mathematics", slug: "mathematics", name: "Mathematics", description: "Numbers, patterns & logic", icon: "∑", active: true },
  { id: "coding", slug: "coding", name: "Coding", description: "Build, debug & think", icon: "</>", active: true },
  { id: "computer-science", slug: "computer-science", name: "Computer Science", description: "Systems, data & the web", icon: "◈", active: true },
];
type SeedQuestion = { id: string; categoryId: string; question: string; answer: string; acceptedAnswers?: string[]; explanation?: string; difficulty: Difficulty; active: boolean };
const entries: Array<[string, string, string, string, string?, Difficulty?]> = [
  ["math-001","mathematics","What is 15% of 200?","30","0.15 × 200 = 30."],["math-002","mathematics","Solve for x: 2x + 4 = 10.","3"],["math-003","mathematics","What is the next prime number after 29?","31","","medium"],["math-004","mathematics","A triangle has angles of 50° and 60°. What is its third angle in degrees?","70"],["math-005","mathematics","Express 0.75 as a simplified fraction.","3/4"],["math-006","mathematics","What is the probability of rolling an even number on a fair six-sided die?","1/2","","medium"],["math-007","mathematics","What is the square root of 144?","12"],["math-008","mathematics","If a $80 item is discounted by 25%, what is the sale price?","60","","medium"],["math-009","mathematics","What is the greatest common divisor of 18 and 24?","6","","medium"],["math-010","mathematics","Solve: 3² + 4² = ?","25"],["math-011","mathematics","What is the area of a rectangle with width 7 and height 5?","35"],["math-012","mathematics","A sequence starts 2, 4, 8, 16. What comes next?","32"],
  ["code-001","coding","In JavaScript, which keyword creates a block-scoped variable that can be reassigned?","let"],["code-002","coding","What data structure follows Last In, First Out (LIFO)?","stack"],["code-003","coding","What is the time complexity of binary search?","O(log n)","","medium"],["code-004","coding","Which HTTP method is conventionally used to create a resource?","POST"],["code-005","coding","What does JSON stand for?","JavaScript Object Notation"],["code-006","coding","In Python, which keyword defines a function?","def"],["code-007","coding","What is a function that calls itself called?","recursive","","medium"],["code-008","coding","Which Git command records staged changes in repository history?","git commit"],["code-009","coding","What TypeScript feature describes an object shape without generating JavaScript?","interface","","medium"],["code-010","coding","What does API stand for?","Application Programming Interface"],["code-011","coding","Which loop is best when iterations are known in advance?","for loop"],["code-012","coding","What keyword exits a loop immediately in many languages?","break"],
  ["cs-001","computer-science","Which operating-system component manages hardware resources?","kernel","","medium"],["cs-002","computer-science","What protocol translates domain names into IP addresses?","DNS"],["cs-003","computer-science","Which database property means a transaction is all-or-nothing?","atomicity","","hard"],["cs-004","computer-science","What does CPU stand for?","Central Processing Unit"],["cs-005","computer-science","What is the smallest unit of data in computing?","bit"],["cs-006","computer-science","What network device forwards packets between networks?","router","","medium"],["cs-007","computer-science","Which data structure uses key-value pairs?","hash table","","medium"],["cs-008","computer-science","What does SQL stand for?","Structured Query Language"],["cs-009","computer-science","What is a process waiting forever for another resource called?","deadlock","","hard"],["cs-010","computer-science","Which cloud model provides virtual machines, storage, and networking?","IaaS","","medium"],["cs-011","computer-science","What is the primary purpose of a firewall?","filter network traffic","","medium"],["cs-012","computer-science","What does RAM stand for?","Random Access Memory"],
];
const questions: SeedQuestion[] = entries.map(([id, categoryId, question, answer, explanation, difficulty]) => ({ id, categoryId, question, answer, explanation: explanation || undefined, difficulty: difficulty ?? "easy", active: true }));
async function seed() { await connectDatabase(); await Category.bulkWrite(categories.map((category) => ({ updateOne: { filter: { id: category.id }, update: { $set: category }, upsert: true } }))); await Question.bulkWrite(questions.map((question) => ({ updateOne: { filter: { id: question.id }, update: { $set: question }, upsert: true } }))); console.log(`Seeded ${categories.length} categories and ${questions.length} questions.`); }
seed().then(() => process.exit(0)).catch((error) => { console.error(error); process.exit(1); });
